Cleanarch
MikhailMishutkin/FoodOrdering pull request #15
Opened 2023-07-25 12:28 UTC by MikhailMishutkin

Работают все сервисы (customer, restaurant, statistics)
Исправлен .gitignore

2023-07-25 12:43 UTC, baibikov requested changes

2023-07-25 12:43 UTC, baibikov commented on cmd/app.go
> +		log.Printf("Failed to register gateway: %v\n", err)
а почему тут просто не вернуть ошибку ? регистрация этих сервисов же важна

2023-07-25 12:43 UTC, baibikov commented on cmd/app.go
> +func StartGRPC(conf configs.Config) {
Если в сигнатуру добавить error, вот так:

```suggestion
func StartGRPC(conf configs.Config) (err error) {
```
то все последующие 
```go
log.Fatal("cannot connect to db: ", err)
```

можно будет заменить на:
```go
return err
```

2023-07-25 12:43 UTC, baibikov commented on cmd/app.go
> +	defer conn.Close()
функция conn.Close() тоже возвращает ошибку, и хорошо бы нам знать о всех ошибках которые могли бы возникнуть.

для того чтобы в последствии отобразить эту ошибку можно использовать пакет multierr, пример:
```go
mutlierr.AppendInto(&err, conn.Close())
```

2023-07-25 12:43 UTC, baibikov commented on cmd/grpcserver/main.go
> +	conf, err := configs.New("./configs/main.yaml.template")
а почему тут принимаем template файл ? этот файл служит только для примера

2023-07-25 12:43 UTC, baibikov commented on cmd/httpserver/main.go
> +	conf, err := configs.New("./configs/main.yaml.template")
тот же вопрос что и в пункте выше

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +	//init stat
на самом деле тут как раз место логам, чтобы было что-то вроде:

```go
logrus.Info("init stat repository")
```

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +	//init stat
вообще всю инициализацию этого воркера лучше вынести  в отдельную функцию:
```go
func run() (err error) {}
```
возвращаемая ошибка необходима, для того, чтобы постоянно не вызывать паники и не писать 
```go
log.Fatal(err)
```

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +		fmt.Errorf("subscribeSync error: %v\n: ", err)
ниже будет паника, если тут не возвращать ошибку

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +			}).GetProduct()
почему бы один раз не съинициализировать ``` StatisticService ```

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +			repo.GetOrder(order)
тут вроде делаем `GetOrder`, но никуда его на самом деле не получаем

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +			continue
в else и так больше ничего нет, `continue` лишний

2023-07-25 12:43 UTC, baibikov commented on cmd/workers/nats.go
> +			}).GetProduct()
+ `GetProduct()` в любом случае может вернуть вернуть ошибку, почему на это нет обработки ?

2023-07-25 12:43 UTC, baibikov commented on internal/customer/handlers/grpc/customer.go
> +	//fmt.Println("функция нью пакета хандлерс_кастомер: ", &client)
вот это лишнее нужно дропнуть

2023-07-25 12:51 UTC, baibikov requested changes

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/grpc/order.go
> +	return &pb.CreateOrderResponse{}, err
красивее будет вот так:

```suggestion
	return &pb.CreateOrderResponse{}, s.cs.CreateOrder(req)
```

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/grpc/order.go
> +		return nil, err
лучше вот так:

```suggestion
		return nil, fmt.Errorf("geting menu from restaurant: %w", err)
```

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/grpc/order.go
> +
вот таких переносов лучше избегать портит читаемость

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/grpc/order.go
> +	var resPb []*pb.Product
лучше заранее выделить под это память так как ты знаешь длину итогового слайза:

```suggestion
	resPb := make([]*pb.Product, 0, len(res))
```

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/grpc/user.go
> +	return &pb.CreateUserResponse{}, err
вот так красивее:

```suggestion
	return new(pb.CreateUserResponse), s.cs.CreateUser(user)
```

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/grpc/user.go
> +	res, err := s.cs.GetUserList(id)
вот тут должна быть проверка на ошибку

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/nats/order.go
> +	fmt.Println(order)
вот это нужно убрать

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/nats/order.go
> +		return err
```suggestion
		return fmt.Errorf("marshal proto message to binary: %w", err)
```

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/nats/order.go
> +	fmt.Println("after marshaling: ", data)
нужно убрать

2023-07-25 12:51 UTC, baibikov commented on internal/customer/handlers/nats/order.go
> +	return err
```suggestion
	return nil
```

2023-07-25 12:51 UTC, baibikov commented on internal/customer/repository/customer_repo.go
> +		log.Fatalf("cannot create tables in gorm: %v\n", err)
почему паника а не возврат ошибки ?

2023-07-25 12:51 UTC, baibikov commented on internal/customer/repository/customer_repo.go
> +	return db, nil
красивее вот так:

```suggestion
	return db,  db.AutoMigrate(&gormdb.User{})
```

2023-07-27 18:56 UTC, MikhailMishutkin commented on internal/customer/handlers/grpc/order.go
> +
вот тут не совсем понял, что о каком переносе речь

2023-07-27 18:59 UTC, MikhailMishutkin commented on internal/customer/handlers/nats/order.go
> +	return err
Объясни, пожалуйста, почему в одном случае мы возвращаем err (я стараюсь так делать), а в другом случае nil? Я так понимаю, что если есть в условиях внутри функции возвраты err, то тогда nil, в остальных случаях err

2023-07-27 19:00 UTC, MikhailMishutkin commented on internal/customer/repository/customer_repo.go
> +		log.Fatalf("cannot create tables in gorm: %v\n", err)
думал, что если миграции не удались, а данные из создаваемых таблиц подтягиваются и другими сервисами, то надо фаталится

2023-08-26 18:12 UTC, closed without merging